name: run_tracker_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  latlong2: ^0.9.1
  flutter_map: ^8.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  geocoding: ^4.0.0
  http: ^1.5.0-beta.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  uuid: ^4.5.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0


flutter:

  uses-material-design: true
